### ISSUE TITLE
homebrew?

### ISSUE THREAD

**Issue by hfm** [hone/mruby-cli#26]
mruby-cli is so great for me! So I need it from [Homebrew](http://brew.sh/)

Like this:

``` rb
# /usr/local/Library/Formula/mruby-cli.rb
require "formula"

class MrubyCli < Formula
  desc "A utility for setting up a CLI with mruby that compiles binaries to Linux, OS X, and Windows"
  homepage "https://github.com/hone/mruby-cli/"
  url "https://github.com/hone/mruby-cli/releases/download/v0.0.3/mruby-cli-0.0.3-i386-apple-darwin14.tgz"
  version "v0.0.3"
  sha256 "6b46ddd15ec17d6ed8cfcf7f200e3fb86281de4ed5f7c25aaf9a70eb180dae4b"

  def install
    bin.install 'mruby-cli'
  end
end
```

**Comment by colinrymer** [comment]
https://github.com/Homebrew/homebrew/pull/46085

**Comment by hone** [comment]
@colinrymer thanks for doing this. Is there something we need to do to keep this up to date? /cc @toch

**Comment by colinrymer** [comment]
Whenever there's a new mruby-cli release, someone will need to update the homebrew formula, but that's a pretty easy process (and something folks using homebrew do a lot).

**Comment by toch** [comment]
@colinrymer we're also working on a osx package, would it make it easier to maintain the formula?

**Comment by zzak** [comment]
Seems like they require a source build for homebrew, but I'm not sure what that implies.

They also mentioned a binary release would be supported under different sources, like cask or homebrew/binary. Also unsure what that would take.

Would be nice to get mruby-cli packages out there in the wild, at set the stage for other tool developers to do that.

**Comment by jeremyjung** [comment]
I attempted to submit mruby-cli as a binary to homebrew cask but it was rejected as they ask open source CLI tools to be submitted to homebrew instead (https://github.com/caskroom/homebrew-cask/pull/35650).  Going through homebrew requires that the applications be able to be compiled on the user's mac as well as on homebrew's MacOS Travis-CLI build setup.  Can the mruby-cli binary be built natively in OSX without docker?  If it can be built in OSX I can submit a new homebrew formula with the compilation steps.  If not, then I can request that the cask PR be reopened due to mruby-cli not being able to be built from OSX without docker.

**Comment by hone** [comment]
Thanks for your interest in getting this into homebrew. In theory you
can dot that, but you'll probably want to comment out all of the other
build options in `build_config.rb`. It's still easiest in docker since
the whole toolchain is setup.

**Comment by jeremyjung** [comment]
Thank you for the help.  I was able to build locally after editing it to just have a single Build.new call with the clang tool chain.

It looks like I'll have to patch build_config.rb in my formula submission which homebrew's audit rules state is not allowed on an initial submission.  I will see if they will make an exception to avoid needing to change the mruby-cli repository.

**Comment by jeremyjung** [comment]
mruby-cli was merged into homebrew today.  You can install it with `brew install mruby-cli`.

**Comment by hone** [comment]
@jeremyjung thanks so much! :heart:
